#!/usr/bin/env bash

# Make sure these 2 values are set correctly or override them as parameters
readonly PROJECT_VERSION="0.0.2"
readonly PROJECT_ROOT=${HOME}/mcast

readonly DOWNLOAD_DIRECTORY=/tmp
readonly JDK_VERSION=19
readonly JDK_DOWNLOAD_URL=https://download.oracle.com/java/${JDK_VERSION}/latest/jdk-${JDK_VERSION}_linux-x64_bin.tar.gz
readonly JDK_DOWNLOAD_FILE=${DOWNLOAD_DIRECTORY}/jdk-${JDK_VERSION}.tar.gz

readonly PROJECT_DOWNLOAD_URL="https://art.aivax.link/artifactory/libs-release-local/link/aivax/learning/scala"

install_jdk() {
  local install_root_directory=${1}
  local jdk_install_directory=${install_root_directory}/jdks
  local jdk_home=${jdk_install_directory}/jdk-${JDK_VERSION}

  if [ -f $JDK_DOWNLOAD_FILE ]; then
     echo "File ${JDK_DOWNLOAD_FILE} exists."
  else
    echo "File ${JDK_DOWNLOAD_FILE} does not exist."
    echo "Downloading it from ${JDK_DOWNLOAD_URL}"
    wget -O ${JDK_DOWNLOAD_FILE} -q ${JDK_DOWNLOAD_URL}
  fi

  mkdir -p "${jdk_home}"
  tar -xf ${JDK_DOWNLOAD_FILE} --strip-components=1 --directory "${jdk_home}"

  ln -sf "${jdk_home}" "${jdk_install_directory}"/jdk-latest
}

install_project() {
  local project_name=${1}
  local project_version=${2}
  local install_root_directory=${3}

  local jdk_install_directory=${install_root_directory}/jdks

  local project_home=${install_root_directory}/projects
  local project_install_directory=${project_home}/install
  local project_config_directory=${project_home}/conf

  # Install Project
  mkdir -p "${project_install_directory}"

  rm -vf "${DOWNLOAD_DIRECTORY}/${project_name}.zip"
  wget -O "${DOWNLOAD_DIRECTORY}/${project_name}.zip" "${PROJECT_DOWNLOAD_URL}/${project_name}/${project_version}/${project_name}-${project_version}.zip"

  unzip -q -o -d "${project_install_directory}" "${DOWNLOAD_DIRECTORY}/${project_name}.zip"

  # Setup Config
  mkdir -p "${project_config_directory}"
  if [ -f "${project_config_directory}/${project_name}.conf" ]; then
     echo "Config file ${project_config_directory}/${project_name}.conf exists."
  else
    echo "Config file ${project_config_directory}/${project_name}.conf does not exists."
    echo "Using the template at ${project_install_directory}/${project_name}/conf/override.sample.conf"
    cp -v "${project_install_directory}/${project_name}/conf/override.sample.conf" "${project_config_directory}/${project_name}.conf"
  fi

  ln -sf "${project_config_directory}/${project_name}.conf" "${project_install_directory}/${project_name}/conf/override.conf"

  # Create run scripts
  touch "${project_home}/${project_name}"
  chmod a+x "${project_home}/${project_name}"

cat > "${project_home}/${project_name}" <<EOF
#!/usr/bin/env bash

pushd ${project_home}/install/${project_name}/bin


( export JAVA_HOME=${jdk_install_directory}/jdk-latest; \\
  \$JAVA_HOME/bin/java --version \\
)

( export JAVA_HOME=${jdk_install_directory}/jdk-latest; \\
  export ALPHAVANTAGE_API_KEY=\${ALPHAVANTAGE_API_KEY}; \\
  export AWS_REGION=\${AWS_REGION}; \\
  export AWS_SECRET_ACCESS_KEY=\${AWS_SECRET_ACCESS_KEY}; \\
  export AWS_ACCESS_KEY_ID=\${AWS_ACCESS_KEY_ID}; \\
  export KMS_ENCRYPTION_KEY=\${KMS_ENCRYPTION_KEY}; \\
 ${project_home}/install/${project_name}/bin/${project_name} \\
)

EOF
}

main() {
  local version="${1:-${PROJECT_VERSION}}"
  local install_root_directory="${2:-"${PROJECT_ROOT}"}"

  install_jdk "${install_root_directory}"

  install_project "multicast-publisher" "${version}" "${install_root_directory}"
  install_project "multicast-receiver" "${version}" "${install_root_directory}"
  install_project "multicast-snooper" "${version}" "${install_root_directory}"
}

main "$@"
