pipeline:
  echo:
    image: sbtscala/scala-sbt:eclipse-temurin-jammy-17.0.9_9_1.9.7_2.13.12
    commands:
      - echo "Using java version:"
      - java -version
      - echo "Using scala version:"
      - scala --version
    when:
      event: [push, pull_request, tag, deployment]

  check:
    image: sbtscala/scala-sbt:eclipse-temurin-jammy-17.0.9_9_1.9.7_2.13.12
    commands:
      - echo "Checking code formatting"
      - mkdir -p .secure_files
      - echo "$sbt_credentials" > .secure_files/sbt_credentials
      - touch .secure_files/sbt_credentials
      - sbt check
    when:
      event: [push, pull_request, tag, deployment]

  test:
    image: sbtscala/scala-sbt:eclipse-temurin-jammy-17.0.9_9_1.9.7_2.13.12
    commands:
      - echo "Running unit tests"
      - mkdir -p .secure_files
      - echo "$sbt_credentials" > .secure_files/sbt_credentials
      - touch .secure_files/sbt_credentials
      - sbt test
    when:
      event: [push, pull_request, tag, deployment]

branches:
  exclude: [ testing/* ]
