pipeline:
  check:
    image: sbtscala/scala-sbt:eclipse-temurin-jammy-17.0.5_8_1.8.2_2.13.10
    commands:
      - sbt check
  test:
    image: sbtscala/scala-sbt:eclipse-temurin-jammy-17.0.5_8_1.8.2_2.13.10
    commands:
      - sbt test

branches:
  exclude: [ testing/* ]
